# SF Housing Intelligence Platform

## Notebook 02 - ETL Validation

### Objective

Explore the cleaned San Francisco Housing Inventory dataset to identify housing patterns, affordability trends, neighborhood differences, and factors influencing rental prices. These insights will guide dashboard development and future machine learning models.

In [2]:
import os
import sys
import pandas as pd

sys.path.insert(0, os.path.abspath("../src"))

from cleaning import (
    clean_monthly_rent,
    clean_square_footage,
    clean_bedroom_count,
    clean_bathroom_count,
    extract_coordinates,
    clean_dates
)

df = pd.read_csv(
    "../data/raw/Rent_Board_Housing_Inventory_20260624.csv"
)

In [43]:
df["monthly_rent_mid"] = clean_monthly_rent(
    df["monthly_rent"]
)

df[
    ["monthly_rent", "monthly_rent_mid"]
].head()

  monthly_rent  monthly_rent_mid
0  $1001-$1250            1125.5
1  $1001-$1250            1125.5
2  $1751-$2000            1875.5
3  $2251-$2500            2375.5
4          NaN               NaN

In [44]:
df["square_footage_mid"] = clean_square_footage(
    df["square_footage"]
)

df[
    ["square_footage", "square_footage_mid"]
].head()

  square_footage  square_footage_mid
0  501-750 Sq.Ft               625.5
1  501-750 Sq.Ft               625.5
2  501-750 Sq.Ft               625.5
3  501-750 Sq.Ft               625.5
4        Unknown                 NaN

In [45]:
df["bedroom_num"] = clean_bedroom_count(
    df["bedroom_count"]
)

df[
    ["bedroom_count", "bedroom_num"]
].head()

  bedroom_count  bedroom_num
0   Two-Bedroom          2.0
1   Two-Bedroom          2.0
2   Two-Bedroom          2.0
3   One-Bedroom          1.0
4           NaN          NaN

In [46]:
df["bathroom_num"] = clean_bathroom_count(
    df["bathroom_count"]
)

df[
    ["bathroom_count", "bathroom_num"]
].head()

  bathroom_count  bathroom_num
0   One bathroom           1.0
1   One bathroom           1.0
2   One bathroom           1.0
3  Two bathrooms           2.0
4            NaN           NaN

In [47]:
coords = extract_coordinates(df["point"])

df = pd.concat([df, coords], axis=1)

In [49]:
df = clean_dates(df)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 546179 entries, 0 to 546178
Data columns (total 34 columns):
 #   Column                               Non-Null Count   Dtype
---  ------                               --------------   -----
 0   unique_id                            546179 non-null  int64
 1   block_num                            546173 non-null  object
 2   unit_count                           546177 non-null  float64
 3   case_type_name                       546179 non-null  object
 4   submission_year                      546179 non-null  int64
 5   block_address                        546102 non-null  object
 6   occupancy_type                       546179 non-null  object
 7   occupancy_or_vacancy_date            443709 non-null  datetime64[ns]
 8   occupancy_or_vacancy_date_year       477014 non-null  object
 9   bedroom_count                        516071 non-null  object
 10  bathroom_count                       516165 non-null  object
 11  square_footage                       545973 non-null  object
 12  monthly_rent                         480259 non-null  object
 13  base_rent_includes_water_sewer       546179 non-null  object
 14  base_rent_includes_natural_gas       546179 non-null  object
 15  base_rent_includes_electricity       546179 non-null  object
 16  base_rent_includes_refuse_recycling  546179 non-null  object
 17  base_rent_includes_other_utilities   38323 non-null   object
 18  past_occupancy                       395257 non-null  object
 19  vacancy_date                         20960 non-null   datetime64[ns]
 20  signature_date                       546045 non-null  datetime64[ns]
 21  occupancy_or_vacancy_date_history    80610 non-null   object
 22  year_property_built                  525720 non-null  float64
 23  point                                546176 non-null  object
 24  analysis_neighborhood                546160 non-null  object
 25  supervisor_district                  546163 non-null  float64
 26  data_as_of                           546179 non-null  datetime64[ns]
 27  data_loaded_at                       546179 non-null  datetime64[ns]
 28  monthly_rent_mid                     472768 non-null  float64
 29  square_footage_mid                   507693 non-null  float64
 30  bedroom_num                          516002 non-null  float64
 31  bathroom_num                         516050 non-null  float64
 32  longitude                            546176 non-null  float64
 33  latitude                             546176 non-null  float64
dtypes: datetime64[ns](5), float64(9), int64(2), object(18)
memory usage: 141.7+ MB

In [51]:
df = clean_dataset(df)

Cleaning monthly rent...
Cleaning square footage...
Cleaning bedrooms...
Cleaning bathrooms...
Extracting coordinates...
Cleaning dates...
Done!

In [52]:
df.to_csv(
    "../data/processed/housing_cleaned.csv",
    index=False
)